name: "Prepare post-release"

on:
  pull_request:
    branches:
      - master
      - v*
    types:
      - closed

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
        contains(github.event.pull_request.labels.*.name, 'release:generate')
    steps:
      - uses: actions/checkout@v3
      - id: pipeline_context
        uses: ./.github/actions/extract_pipeline_context
        with:
          last_minor: ${{ contains(github.event.pull_request.labels.*.name, 'release:generate-last_minor') }}
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: "dev_tools/Gemfile"
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: "Bump to the development version"
        run: |
          cd dev_tools/ && bin/bump-to-dev-version \
            ${{ steps.pipeline_context.outputs.next_candidate_dev_version }}
      - name: "Bump previous solidus minor version"
        if: github.ref_name == 'master'
        run: |
          cd dev_tools/ && bin/bump-previous-minor-version \
            ${{ steps.pipeline_context.outputs.candidate_minor_version }}
      - name: "Bump to the development version in docker-compose"
        if: github.ref_name == 'master'
        run: |
          cd dev_tools/ && bin/bump-docker-image-to-dev-version \
            ${{ steps.pipeline_context.outputs.next_candidate_dev_version }}
      - name: "Bump installer starter frontend version"
        if: github.ref_name == 'master'
        run: |
          cd dev_tools/ && bin/bump-starter-frontend-version \
            main
      - name: "Publish release draft & tag last commit"
        run: |
          cd dev_tools/ && bin/publish-release \
            ${{ github.token }} \
            ${{ github.repository }} \
            ${{ steps.pipeline_context.outputs.candidate_tag }}
      - name: "Create patch branch"
        if: github.ref_name == 'master'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          candidate_patch_branch="${{ steps.pipeline_context.outputs.candidate_patch_branch }}"
          git checkout -b $candidate_patch_branch
          git push --set-upstream origin $candidate_patch_branch
      - name: "Create PR for master"
        uses: ./.github/actions/commit_and_submit_pull_request
        with:
          labels: changelog:skip
          message: |
            Post-release chores after having released Solidus ${{ steps.pipeline_context.outputs.candidate_tag }}
            
            
            This code has been automatically generated by our 'Prepare post-release' GitHub
            action.
            
            Make sure that:
            
            - [ ] The new release has been published, along with its tag. See https://github.com/${{ github.repository }}/releases/tag/${{ steps.pipeline_context.outputs.candidate_tag }}
            - [ ] The corresponding patch branch exists. See https://github.com/${{ github.repository }}/tree/${{ steps.pipeline_context.outputs.candidate_patch_branch }}
